// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSwBmxgAlsm82dyG4aCvn50hY2ri4y0pI',
    appId: '1:2338770254:web:f943663a3c62099870e21f',
    messagingSenderId: '2338770254',
    projectId: 'blobs-78b7d',
    authDomain: 'blobs-78b7d.firebaseapp.com',
    storageBucket: 'blobs-78b7d.firebasestorage.app',
    measurementId: 'G-XKYMZT9676',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCijRLFFRgVmKuDImt41TO7mz_pXKiw_NY',
    appId: '1:2338770254:android:df6e0f137359d5a670e21f',
    messagingSenderId: '2338770254',
    projectId: 'blobs-78b7d',
    storageBucket: 'blobs-78b7d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCD3L3mWUq4nFjBc_I8o2Hl5rakpDiojiY',
    appId: '1:2338770254:ios:536a0f9394fe401270e21f',
    messagingSenderId: '2338770254',
    projectId: 'blobs-78b7d',
    storageBucket: 'blobs-78b7d.firebasestorage.app',
    iosBundleId: 'com.blobhousegames.blobs',
  );
}
